expose_plugin:
    clientSecret: 2y5wvlnds8cgwwwwgsc4wgcco4c8gswgww4c48c8osgoocc88s
    clientId: aina-test_1buc6x7by0tcoccog444skg8g4sgg8gsos08cs4c88gc8s4w0c
    exposeBaseUri: 'http://51.15.221.219:8150'
    token: NDIwMjQwNWQ3NDBkMjRlNjdmMzA0ZGZjZTdjYTkxNDljNDBiM2E4ZjU5NTk1NDIxNWY3MjAwNjcwNzUxZmU1NQ

# example of jsondata to create publication

  {
      "title": "the title",
      "enabled": true,
      "layout": "gallery",
      "publiclyListed": true,
      "slug": "",
      "securityMethod": "",
      "securityOptions": {}
  }
